### ISSUE TITLE
chromiumkeydump masterkey

### ISSUE THREAD

**Issue by ghost** [crypt0p3g/bof-collection#1]
chromiumkeydump master key outputs nothing.

cookies working login data is ok, but dump mastery outputs only the banner for the command.
any help please?

**Comment by nheiniger** [comment]
Happened to me as well. Make sure that your BOF is compiled with the correct name and placed in the `bin/` folder as specified in the readme. If in doubt, check in the aggressor script to make sure it's correct.

**Comment by crypt0p3g** [comment]
Sorry for not being clear.
Yes, you should put the binaries (ChromiumKeyDump.x64.o, ChromiumKeyDump.o), under the bin (needs to be created in the same folder with cna file).

File structure example:
```
./bin/ChromiumKeyDump.x64.o
./bin/ChromiumKeyDump.o

./src/ChromiumKeyDump.cpp
./src/beacon.h
./ChromiumKeyDump.cna
```

**Comment by nheiniger** [comment]
I was clear if one read the readme carefully or simply by having a look at the code ^^'
