### ISSUE TITLE
Option of specific path on ChromiumKeyDump

### ISSUE THREAD

**Issue by CUHKJason** [crypt0p3g/bof-collection#2]
From a recent experience, I encountered a situation that the Chrome folder is not located in the %localappdata% but a mounted drive that the current implementation could not extract the Masterkey.
In the Chlonium tool, the path to the Local State key could be specified in order to handle this case, so I wonder if this feature could be added to this bof too.
I can submit a [pr](https://github.com/CUHKJason/bof-collection/commit/017ab2de09952b3f671448b712fe003462bb7403) if you are happy with this.

![output](https://user-images.githubusercontent.com/19466939/193981372-0d8de3d6-38f2-4828-a4df-974efc5ba1cc.png)

**Comment by crypt0p3g** [comment]
Thank you.
Merged with your code!
