### ISSUE TITLE
Errors when compiling with mingw

### ISSUE THREAD

**Issue by carlnykvist** [crypt0p3g/bof-collection#3]
Hi,

I tried compiling with the command you have in your README: x86_64-w64-mingw32-gcc -c ChromiumKeyDump.cpp -o ChromiumKeyDump.x64.o

But get the below error. Anything I should change?

![image](https://user-images.githubusercontent.com/5971228/205497481-e5ca16be-8c9e-4215-91de-a82f95b8bd8a.png)

**Comment by crypt0p3g** [comment]
Hello, thank you for pointing!
It was dev code and had some bugs all around:)
Should be fixed now!

**Comment by carlnykvist** [comment]
Thank you!
